
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace UpdateMember.Models.FEDSMBR
{

using System;
    using System.Collections.Generic;
    
public partial class MemberCellphoneValid
{

    public int Id { get; set; }

    public int MemberId { get; set; }

    public string Cellphone { get; set; }

    public string Code { get; set; }

    public System.DateTime ExpireDate { get; set; }

    public Nullable<System.DateTime> ValidDate { get; set; }



    public virtual Member Member { get; set; }

}

}
