
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace UpdateMember.Models.FEDSMBR
{

using System;
    using System.Collections.Generic;
    
public partial class Member
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Member()
    {

        this.MemberCellphoneValid = new HashSet<MemberCellphoneValid>();

        this.MemberEmailValid = new HashSet<MemberEmailValid>();

        this.MemberToken = new HashSet<MemberToken>();

    }


    public int Id { get; set; }

    public string Cellphone { get; set; }

    public string Email { get; set; }

    public string Account { get; set; }

    public string Password { get; set; }

    public string Name { get; set; }

    public string Gender { get; set; }

    public Nullable<System.DateTime> Birthday { get; set; }

    public string RocId { get; set; }

    public string ZipCode { get; set; }

    public string City { get; set; }

    public string Area { get; set; }

    public string Road { get; set; }

    public string Address { get; set; }

    public string MobileCarrier { get; set; }

    public int NotifySMS { get; set; }

    public int NotifyDM { get; set; }

    public string FbId { get; set; }

    public string GeId { get; set; }

    public string LineId { get; set; }

    public string AppleId { get; set; }

    public string HgpId { get; set; }

    public string ApId { get; set; }

    public string TempHgCardNo { get; set; }

    public string HgCardNo { get; set; }

    public Nullable<System.DateTime> HgAgreeDate { get; set; }

    public Nullable<System.DateTime> HgValidDate { get; set; }

    public Nullable<System.DateTime> RealValidDate { get; set; }

    public Nullable<System.DateTime> PdpAgreeDate { get; set; }

    public string PersonContactId { get; set; }

    public string EventNo { get; set; }

    public System.DateTime CreateDate { get; set; }

    public Nullable<System.DateTime> EditDate { get; set; }

    public string LastAccessIP { get; set; }

    public int Status { get; set; }

    public string Note { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MemberCellphoneValid> MemberCellphoneValid { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MemberEmailValid> MemberEmailValid { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MemberToken> MemberToken { get; set; }

}

}
