//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateMember.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GiftsEntities : DbContext
    {
        public GiftsEntities()
            : base("name=GiftsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GroupAuth_Main> GroupAuth_Main { get; set; }
        public virtual DbSet<GroupAuth_Setting> GroupAuth_Setting { get; set; }
        public virtual DbSet<UserInfo_Main> UserInfo_Main { get; set; }
        public virtual DbSet<UserInfo_Setting> UserInfo_Setting { get; set; }
    }
}
